### PR TITLE
Drop compatibility code

### PR DESCRIPTION
**Pull request by ekohl**

### CODE REVIEW

**Comment by adamruzicka** [comment]
Looks good to me, but rubocop is unhappy

**Comment by ekohl** [comment]
Do you want me to open a Redmine issue as well?

**Comment by ekohl** [comment]
Updated. I didn't update Rubocop to the latest version and didn't add the frozen strings but did use the safe navigator.

**Comment by adamruzicka** [comment]
I wouldn't insist on having an issue, but you were too fast, thanks.

**Review by adamruzicka — APPROVED** [review]
ACK

**Comment by adamruzicka** [comment]
Thank you @ekohl !

**Pull request merged**
