### PR TITLE
Rewrite test suite using reusable actions

### PR DESCRIPTION
**Pull request by ekohl**
This partly replaces https://github.com/theforeman/smart_proxy_dynflow/pull/104.

### CODE REVIEW

**Comment by ekohl** [comment]
The failures on Ruby 3.2 and Ruby 3.0 are unexpected. The `--strict` check was apparently added on Ruby 2.6, but as we're dropping Ruby 2.5 I'm not going to fix it.

**Comment by adamruzicka** [comment]
This now needs a rebase

**Comment by ekohl** [comment]
@adamruzicka do we want to continue requiring Redmine issues in this repo? Otherwise this is green.

**Comment by adamruzicka** [comment]
In general I'm fine with letting it slide for internal things like this but I'd like to continue requiring them for user facing changes.

**Review by adamruzicka — APPROVED** [review]

**Pull request merged**
