### PR TITLE
Fixes #32565 - Collect chunked outputs

### PR DESCRIPTION
**Pull request by adamruzicka**
Requires:
- [x] https://github.com/Dynflow/dynflow/pull/387

### CODE REVIEW

**Review by ezr-ondrej — APPROVED** [review]
I guess this is ready to merge?

**Comment by adamruzicka** [comment]
Not sure what the failures are about, tests seem to be passing for me locally [test smart_proxy_dynflow]

**Comment by ezr-ondrej** [comment]
> Not sure what the failures are about, tests seem to be passing for me locally [test smart_proxy_dynflow]

From what I'm reading the execution_plan is not persisted prior the planinning?
That would result in the execution plan id not being in the database and thus actions foreign_key failure.
Why it complains now I've got no idea :thinking:

**Comment by adamruzicka** [comment]
With dynflow-1.6.1 out, [test smart_proxy_dynflow] should turn green too.

**Comment by adamruzicka** [comment]
:green_apple:

**Comment by adamruzicka** [comment]
I'll take the liberty of considering the previous approval as still valid and go ahead and merge this

**Pull request merged**
