### PR TITLE
Update Rubocop, and add minitest reporters

### PR DESCRIPTION
**Pull request by archanaserver**
cherry-picked from f91f0e2abf4edec4417e79cc6bb8cbd53683967b

Based on: #121

### CODE REVIEW

**Comment by ehelms** [comment]
Looks like you will need to address the Rubocop error before we can see if the tests pass.

**Comment by archanaserver** [comment]
> Looks like you will need to address the Rubocop error before we can see if the tests pass.

@ehelms rubocop error is fixed now!

**Comment by archanaserver** [comment]
@ehelms yes this worked with this simpler way. Thanks!

Also now it just need rubocop version update, which needs some offenses to resolve to satisfy fully, here I have already committed this changes https://github.com/theforeman/smart_proxy_dynflow/pull/121/commits/1dabb8c397e587ca40c31c5a730bda2f6f0add0f#diff-d09ea66f8227784ff4393d88a19836f321c915ae10031d16c93d67e6283ab55fR5-R11

**Comment by ehelms** [comment]
[test smart_proxy_dynflow]

**Comment by ehelms** [comment]
Let's at least update Ruby 3.1 on Jenkins to latest 3.1.4 to match what Github Actions is using: https://github.com/theforeman/foreman-infra/pull/1850

**Comment by ehelms** [comment]
[test smart_proxy_dynflow]

**Review by ekohl — COMMENTED** [review]
This PR now contains the update to Ruby 3. I'd try to keep that out of this PR and keep it minimal.

A while back I submitted https://github.com/theforeman/smart_proxy_dynflow/pull/104 which contains some work to update RuboCop and only utilizes the existing (passing) GH Actions. I'd recommend starting with that. In the next PRs you can add the `jenkins:unit` task and then change the Ruby version matrix.

I'll also admit I really like the GH annotations for failed RuboCop rules, which you can see in my PR.

**Comment by ehelms** [comment]
The failure is on 3.1, so I think if you do as suggested and pull out https://github.com/theforeman/smart_proxy_dynflow/pull/122/commits/fb5cbf6db8383f7b9fc6431aa181e6a844ea4b15 from the set of commits, that this will focus this PR on the Rubocop updates + changes to get tests running and passing. Then a dedicated Ruby 3 PR can be opened with a smaller diff and allow debugging the test failure easier.

**Comment by archanaserver** [comment]
@ehelms @ekohl I've moved Ruby changes from this PR to #123. 
Also about the jenkins failure, it is something related to timeout coming from here https://github.com/theforeman/smart_proxy_dynflow/blob/master/test/process_manager_test.rb#L109-L111. I tried debugging looking at Dynflow gem version and some other ways to but that didn't worked.

**Comment by ehelms** [comment]
The branch that is failing is Ruby 3.1, maybe we need to just accept an dignore this failure for now and try to address it here? https://github.com/theforeman/smart_proxy_dynflow/pull/123

@ekohl what do you think about that strategy? Our CI is already updated to test Ruby 3, but the project itself has not been updated, so it's a bit of a chicken-egg

**Comment by ekohl** [comment]
@ehelms I'm not sure where I said it, but if it's only about Ruby 3.1 then it's not a blocker to merging it.

**Review by ehelms — APPROVED** [review]

**Pull request merged**
