### PR TITLE
Include docs in gem, don't include Gemfile

### PR DESCRIPTION
**Pull request by stbenjam**

### CODE REVIEW

**Comment by stbenjam** [comment]
I'm not really sure about the Gemfile change, see https://github.com/theforeman/smart_proxy_remote_execution_ssh/pull/3#issuecomment-132662662

**Comment by jlsherrill** [comment]
ACK

**Comment by domcleal** [comment]
The PR test will no longer run on Ruby 1.8/1.9.2 soon, please ignore the failure for now.  Re-testing in an hour's time from this comment should see it fixed, if you wish to check.

**Comment by ares** [comment]
[test]

**Comment by mmoll** [comment]
what's the status here?

**Comment by ares** [comment]
@stbenjam would you mind rebasing?

**Comment by stbenjam** [comment]
Old, structure of the gem is a lot different now - closing.

**Pull request closed without merging**
