### PR TITLE
Fixes #15424 - Be able to daemonize

### PR DESCRIPTION
**Pull request by adamruzicka**

### CODE REVIEW

**Comment by stbenjam** [comment]
Hmm, when I try this:

[root@centos6-koji ~]# service smart_proxy_dynflow_core start
Starting smart_proxy_dynflow_core:                         [  OK  ]
[root@centos6-koji ~]# service smart_proxy_dynflow_core status
smart_proxy_dynflow_core is stopped

This is all I see: 

[2016-06-16 12:05:40.283 #9035]  WARN -- Could not open DB for dynflow at '', will keep data in memory. Restart will drop all dynflow data.
[2016-06-16 12:05:40.344 #9035] DEBUG -- Using HTTP
[2016-06-16 12:05:58.595 #9188]  WARN -- Could not open DB for dynflow at '', will keep data in memory. Restart will drop all dynflow data.
[2016-06-16 12:05:58.662 #9188] DEBUG -- Using HTTP
[2016-06-16 12:06:31.953 #9352]  WARN -- Could not open DB for dynflow at '', will keep data in memory. Restart will drop all dynflow data.
[2016-06-16 12:06:32.015 #9352] DEBUG -- Using HTTP

**Comment by stbenjam** [comment]
Nevermind, got it working!

[root@centos6-koji ~]# service smart_proxy_dynflow_core status
smart_proxy_dynflow_core (pid  9754) is running...


I had the PID file misconfigured in the init script.

The init scripts need some changes to support this, I can open a PR to your branch once I get back after breakfast.

**Comment by adamruzicka** [comment]
Glad to hear you got it working. Having a PR for those changes would be great

**Comment by stbenjam** [comment]
From my perspective this is good, ACK from me.  Anyone else want to take a look as well? @ares @iNecas

**Comment by iNecas** [comment]
I'm trying to test this with installer changes as well on centos6, I will ack it after everything works there

**Comment by iNecas** [comment]
I've got it running but the proxy is not performing the work: my guess is we initialize something before damonizoation happens, which closes some file descriptors, looking into it right now

**Comment by adamruzicka** [comment]
Maybe that's the reason why smart proxy always passes `:daemonize => false` to rack and handles the forking on its own

**Comment by iNecas** [comment]
@adamruzicka I've opened a PR with the changes of this one - the merge commit + fix for the initialization https://github.com/theforeman/smart_proxy_dynflow/pull/20: I wasn't sure how much time to you have till next week. Let me know if you prefer opening a PR against this PR

**Comment by adamruzicka** [comment]
Closing in favor of #20

**Pull request closed without merging**
