### PR TITLE
Support for providing task status on demand

### PR DESCRIPTION
**Pull request by adamruzicka**

### CODE REVIEW

**Comment by jlsherrill** [comment]
Out of curiosity what's the reason to add this?

**Comment by jlsherrill** [comment]
Not sure why but I was testing this and can't get it to work:
create a task:
```
jlsherri~/git/smart_proxy_dynflow (master)$ curl http://localhost:8001/dynflow/tasks       -X POST -H 'Content-Type: application/json'      -d '{"action_name":  "Proxy::RemoteExecution::Ssh::CommandAction", "action_input": {"task_id" : "1234'$RANDOM'",
                "script": "ls \"/home/jlsherri/\"",
                 "hostname": "localhost",
                 "effective_user": "jlsherri"}}'
{"task_id":"c6f168f1-5ba4-424e-a401-a0aeb7a770c0"}
```
but:
```
curl -X GET http://localhost:8001/dynflow/tasks/c6f168f1-5ba4-424e-a401-a0aeb7a770c0/status
```
throws a 404.  I'm sure 'm just doing something wrong :)

**Comment by jlsherrill** [comment]
Actually checking out your PR would help when trying to test it! ;)

ACK

**Comment by adamruzicka** [comment]
@jlsherrill Thanks for looking into it.

The reason for opening this PR was that I needed to have a possibility to check the task's status on timeout and handle the situation accordingly (cancel the task if its running, process the data and update the foreman tasks task if it is not, etc...)

**Comment by jlsherrill** [comment]
Thanks @adamruzicka

**Pull request merged**
