### PR TITLE
Fixes #32961 - Groundwork for async batch triggering

### PR DESCRIPTION
**Pull request by adamruzicka**

### CODE REVIEW

**Comment by adamruzicka** [comment]
Does it make sense to have separate sync and async variants or should we just switch from one to the other once it is available?

**Comment by adamruzicka** [comment]
[test smart_proxy_dynflow]

**Comment by adamruzicka** [comment]
:green_apple:

**Review by ezr-ondrej — APPROVED** [review]
:shipit:

**Pull request merged**
